# permissions for end users to edit counters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: counter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: etcd-bench
    app.kubernetes.io/part-of: etcd-bench
    app.kubernetes.io/managed-by: kustomize
  name: counter-editor-role
rules:
- apiGroups:
  - etcd-bench.my.domain
  resources:
  - counters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd-bench.my.domain
  resources:
  - counters/status
  verbs:
  - get
