# permissions for end users to view writers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: writer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: etcd-bench
    app.kubernetes.io/part-of: etcd-bench
    app.kubernetes.io/managed-by: kustomize
  name: writer-viewer-role
rules:
- apiGroups:
  - etcd-bench.my.domain
  resources:
  - writers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd-bench.my.domain
  resources:
  - writers/status
  verbs:
  - get
